arm-autonomy: Fix xenguest volume check on boot
Fix xenguest-manager to only check the device configured to be used for
LVM volumes for guests when a guest is created which needs it.

This prevent the manager doing errors during boot when the volume does
not exist even if it is not used by any guest.

Change-Id: Ibc285887836ea40595634412dcfa7ee9039dc220
Issue-Id: SCM-956
Signed-off-by: Bertrand Marquis <bertrand.marquis@arm.com>
Reviewed-by: Diego Sueiro <diego.sueiro@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>

diff --git a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
--- a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
+++ b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
@@ -19,17 +19,6 @@ source ${XENGUEST_CONF_BASE}/xenguest-manager.conf
 
 PREF="xenguest:"
 
-if [ -z "${XENGUEST_VOLUME_DEVICE:-}" -o \
-    ! -b ${XENGUEST_VOLUME_DEVICE:-} ]; then
-    echo "${PREF} Invalid volume device in configuration: ${XENGUEST_VOLUME_DEVICE:-}"
-    exit 1
-fi
-
-if [ -z "${XENGUEST_VOLUME_NAME:-}" ]; then
-    echo "${PREF} No volume name in configuration, using vg-xen..."
-    XENGUEST_VOLUME_NAME="vg-xen"
-fi
-
 function usage() {
     cat <<EOF
 Usage $this ACTION [OPTIONS]
@@ -67,6 +56,17 @@ EOF
 
 function xenguest_volume_init()
 {
+    if [ -z "${XENGUEST_VOLUME_DEVICE:-}" -o \
+        ! -b ${XENGUEST_VOLUME_DEVICE:-} ]; then
+        echo "${PREF} Invalid volume device in configuration: ${XENGUEST_VOLUME_DEVICE:-}"
+        exit 1
+    fi
+
+    if [ -z "${XENGUEST_VOLUME_NAME:-}" ]; then
+        echo "${PREF} No volume name in configuration, using vg-xen..."
+        XENGUEST_VOLUME_NAME="vg-xen"
+    fi
+
     pvs ${XENGUEST_VOLUME_DEVICE} > /dev/null 2>&1
     if [ $? -ne 0 ]; then
         echo "${PREF} Initialize lvm on ${XENGUEST_VOLUME_DEVICE}"
