arm-autonomy: xenguest-mgr: Add support for compressed partition images
xenguest-manager now can create guest partition
using compressed images like *.img.gz or *.img.bz2.

Change-Id: Ifaec0b7c301b2b316ebccdd0ca85083262f2714c
Signed-off-by: Kamil Dziezyk <kamil.dziezyk@arm.com>
Reviewed-by: Bertrand Marquis <bertrand.marquis@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>

diff --git a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
--- a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
+++ b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
@@ -262,12 +262,30 @@ function xenguest_disk_init()
             fi
 
             case ${content} in
-                *.img)
+                *.img*)
+                    decompress=""
+                    case ${content} in
+                        *.img.gz)
+                            decompress='zcat'
+                            ;;
+                        *.img.bz2)
+                            decompress='bzcat'
+                            ;;
+                        *.img)
+                            decompress='cat'
+                            ;;
+                        *)
+                            # invalid/unknown compression type
+                            echo "${PREF} Invalid file format in disk ${content}"
+                            xenguest_detach_disk
+                            exit 1
+                            ;;
+                    esac
                     # dd into partition
                     echo "xenguest-mkimage extract-disk-file ${guestfile} " \
-                        "${content} | dd of=/dev/xvda${part} " >> ${LOGFILE} 2>&1
+                        "${content} | ${decompress} | dd of=/dev/xvda${part} " >> ${LOGFILE} 2>&1
                     xenguest-mkimage extract-disk-file ${guestfile} ${content} \
-                        | dd of=/dev/xvda${part} >> ${LOGFILE} 2>&1
+                        | ${decompress} | dd of=/dev/xvda${part} >> ${LOGFILE} 2>&1
                     if [ $? -ne 0 ]; then
                         echo "${PREF} Cannot populate partition ${part}"
                         xenguest_detach_disk
