arm-autonomy/xenguest-tools: set guest disk and partition sizes in MB or GB
This patch brings following improvements:
 * Allow user to set guest disk and partition sizes in MB or GB.
 * Documentation update about this improvement.

Change-Id: I0a1a2945022efcd9d32bb39404b4a85721e28e19
Issue-Id: SCM-1515
Signed-off-by: Kamil Dziezyk <kamil.dziezyk@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>

diff --git a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
--- a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
+++ b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-manager
@@ -54,6 +54,47 @@ with ACTION being one of:
 EOF
 }
 
+is_integer() {
+    if ! [[ "${1}" =~ ^[0-9]+$ ]]; then
+        >&2 echo "error: invalid number '${1}'"; exit 1
+    fi
+}
+
+# check size and convert it to MB, e.g '1[G]' => '1000M'
+check_size() {
+    local disksize="${1}"
+
+    [ -n "${disksize}" ] || disksize="invalid"
+
+    # disksize may have appended M or G suffix, let's extract it
+    # ${var:offset:length}, where #var is var length
+    local lastchar="${disksize:${#disksize}-1}"
+    case "${lastchar}" in
+        [0-9])
+            # backwards compatibility
+            is_integer "${disksize}"
+            echo -e "$((${disksize} * 1000))M"
+            return
+            ;;
+        G|M)
+            if [ "${#disksize}" -gt "1" ]; then
+                local size="${disksize::${#disksize}-1}"
+                is_integer "${size}"
+                # convert GB to MB
+                [ "${lastchar}" = "M" ] || size=$((${size} * 1000))
+                echo -e "${size}M"
+                return
+            fi
+            ;;
+        *)
+            ;;
+    esac
+
+    >&2 echo -e "Invalid size format '${1}'" \
+                "\n\tSupported size format is e.g 1000M or 2[G]"
+    exit 1
+}
+
 function xenguest_volume_init()
 {
     # Return:
@@ -142,7 +183,8 @@ function xenguest_disk_init()
 
     source ${XENGUEST_CONF_BASE}/guests/${guestname}/disk.cfg
 
-    if [ ${DISK_SIZE:-0} -eq 0 ]; then
+    DISK_SIZE=$(check_size "${DISK_SIZE}")
+    if [ -z "${DISK_SIZE}" ] || [ "${DISK_SIZE}" = "0M" ]; then
         echo "${PREF} No disk for ${guestname}"
         return
     fi
@@ -172,9 +214,9 @@ function xenguest_disk_init()
     fi
 
     # Create volume
-    echo "lvcreate -y -L ${DISK_SIZE}G -n ${guestname} ${XENGUEST_VOLUME_NAME}" \
+    echo "lvcreate -y -L ${DISK_SIZE} -n ${guestname} ${XENGUEST_VOLUME_NAME}" \
         >> ${LOGFILE} 2>&1
-    lvcreate -y -L ${DISK_SIZE}G -n ${guestname} ${XENGUEST_VOLUME_NAME} \
+    lvcreate -y -L ${DISK_SIZE} -n ${guestname} ${XENGUEST_VOLUME_NAME} \
         >> ${LOGFILE} 2>&1
     if [ $? -ne 0 ]; then
         echo "${PREF} Error creating volume ${guestname}"
@@ -212,9 +254,11 @@ function xenguest_disk_init()
         fstype=$(echo ${partdesc} | sed -e "s/.*:\(.*\):.*/\1/")
         content=$(echo ${partdesc} | sed -e "s/.*:.*:\(.*\)/\1/")
 
-        if [ "${size}" -ne 0 ]; then
-            # Size is expressed in GB, pass it in MB
-            size=$(expr ${size} \* 1024)
+        size=$(check_size "${size}")
+        if [ -n "${size}" ] && [ "${size}" != "0M" ]; then
+            # size has appended M or G suffix, let's extract just the value
+            # ${var:offset:length}, where #var is var length
+            size="${size::${#size}-1}"
             partend=$(expr ${partstart} + ${size})
 
             # Let first MB of disk free for partition table
diff --git a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
--- a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
+++ b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
@@ -110,7 +110,8 @@ Init configuration
 
 Disk configuration
 --disk-reset-config     reset disk guest configuration to default (no disk)
---disk-size=SZ          set guest disk size (in GB)
+--disk-size=SZ          set guest disk size in MB or GB(default),
+                         e.g 1000M or 2[G].
 --disk-device=DEV       set device to be used to create the guest disk
                         if unset or set to an empty string, the volume will be
                         create in the default manager volume group.
@@ -368,6 +369,47 @@ disk_config_reset() {
 disk_config_rm_part() {
     partid=$1
     sed -i "/DISK_PART${partid}=.*/d" ${IMAGE_TMPDIR}/disk.cfg
+}
+
+is_integer() {
+    if ! [[ "${1}" =~ ^[0-9]+$ ]]; then
+        >&2 echo "error: invalid number '${1}'"; exit 1
+    fi
+}
+
+# check size and convert it to MB, e.g '1[G]' => '1000M'
+check_size() {
+    local disksize="${1}"
+
+    [ -n "${disksize}" ] || disksize="invalid"
+
+    # disksize may have appended M or G suffix, let's extract it
+    # ${var:offset:length}, where #var is var length
+    local lastchar="${disksize:${#disksize}-1}"
+    case "${lastchar}" in
+        [0-9])
+            # backwards compatibility
+            is_integer "${disksize}"
+            echo -e "$((${disksize} * 1000))M"
+            return
+            ;;
+        G|M)
+            if [ "${#disksize}" -gt "1" ]; then
+                local size="${disksize::${#disksize}-1}"
+                is_integer "${size}"
+                # convert GB to MB
+                [ "${lastchar}" = "M" ] || size=$((${size} * 1000))
+                echo -e "${size}M"
+                return
+            fi
+            ;;
+        *)
+            ;;
+    esac
+
+    >&2 echo -e "Invalid size format '${1}'" \
+                "\n\tSupported size format is e.g 1000M or 2[G]"
+    exit 1
 }
 
 disk_config_add_part() {
@@ -742,7 +784,9 @@ for arg in "${@}"; do
             disk_config_reset
             ;;
         --disk-size=*)
-            sed -i "s/DISK_SIZE=.*/DISK_SIZE=\"${optarg}\"/" \
+            size=$(check_size "${optarg}")
+            [ -n "size" ] || exit 1
+            sed -i "s/DISK_SIZE=.*/DISK_SIZE=\"${size}\"/" \
                 ${IMAGE_TMPDIR}/disk.cfg
             ;;
         --disk-device=*)
