arm-autonomy/xenguest-mkimage: add extra ramdisk support
Some guest images requires a ramdisk, that is built with a custom recipe.
This patch adds an option '--xen-ramdisk',
for xenguest-mkimage script to cover that.
Extra ramdisk support is also added to xenguest-image-extra bbclass,
via 'XENGUEST_EXTRA_RAMDISK' variable.

Issue-Id: SCM-1276
Change-Id: I8ec74a37c0c96ca83a3489911186f3b3262f80fd
Signed-off-by: Kamil Dziezyk <kamil.dziezyk@arm.com>
Reviewed-by: Diego Sueiro <diego.sueiro@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>

diff --git a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
--- a/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
+++ b/meta-arm-autonomy/recipes-extended/xenguest/files/xenguest-mkimage
@@ -82,6 +82,9 @@ Xen configuration for the guest
 --xen-device-tree=      disable device tree parameter in xen configuration
 --xen-device-tree=FILE  set guest device tree in xen configuration and add
                          file to xen files
+--xen-ramdisk=          disable ramdisk parameter in xen configuration
+--xen-ramdisk=FILE      set guest ramdisk in xen configuration and add
+                         file to xen files
 --xen-disk=             disable disk parameter in xen configuration
 --xen-disk=DEV          set guest disk to device DEV (phy:DEV,xvda,w is set)
 --xen-append=FILE       append FILE content to xen configuration
@@ -666,6 +669,20 @@ for arg in "${@}"; do
                 xen_config_set_string "device_tree" "files/guest.dtb"
                 mkdir -p ${IMAGE_TMPDIR}/files
                 install -m 644 ${optarg} ${IMAGE_TMPDIR}/files/guest.dtb
+            fi
+            ;;
+        --xen-ramdisk=*)
+            if [ -z "${optarg}" ]; then
+                xen_config_disable_param "ramdisk"
+                rm -f ${IMAGE_TMPDIR}/files/ramdisk.img
+            else
+                if [ ! -f ${optarg} ]; then
+                    echo "Error: invalid ramdisk file ${optarg}"
+                    exit 1
+                fi
+                xen_config_set_string "ramdisk" "files/ramdisk.img"
+                mkdir -p ${IMAGE_TMPDIR}/files
+                install -m 644 ${optarg} ${IMAGE_TMPDIR}/files/ramdisk.img
             fi
             ;;
         --xen-disk=*)
